name: Semantic Release CI

on:
  push:
    branches: [ main ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: npx semantic-release